- 👋 Hi, I’m @karinkaacom
- 👀 I’m interested in manager resource
- 🌱 I’m currently learning in university
- 💞️ I’m looking to collaborate on aspire to be a recruiter in the center of the armed forces
- 📫 How to reach me need go to Kyiv
- 😄 Pronouns: good job
- ⚡ Fun fact: I'm pianist and creator

<!---
karinkaacom/karinkaacom is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
